  
apiVersion: constraints.gatekeeper.sh/v1beta
kind: FernandoTestPodEnforceLabels
metadata:
  name: fernandotestpodenforcelabels
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
      - key: control-plane
        operator: DoesNotExist
  parameters:
    labels: [ "label1", "label2" ]
