apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: fernandotestpodenforcelabels
spec:
  crd:
    spec:
      names:
        kind: FernandoTestPodEnforceLabels
        listKind: FernandoTestPodEnforceLabelsList
        plural: FernandoTestPodEnforceLabels
        singular: FernandoTestPodEnforceLabels
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            labels:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package fernandotestpodenforcelabels

        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          input.review.object.metadata.namespace != "kube-system"
          required := {label | label := input.parameters.labels[_]}
          provided := {label | input.review.object.metadata.labels[label]}
          missing := required - provided
          count(missing) > 0
          msg := sprintf("you must provide labels: %v", [missing])
        }
